# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestNewTest():

def setup_method(self, method):
  self.driver = webdriver.Chrome()
  self.vars = {}

def teardown_method(self, method):
  self.driver.quit()

  def test_newTest(self):
    self.driver.get("http://www.google.com/")
    self.driver.find_element(By.ID, "APjFqb").click()
    self.driver.find_element(By.ID, "APjFqb").send_keys("chatgpt")
    self.driver.find_element(By.CSS_SELECTOR, "#ERWdKc > .wM6W7d > span").click()
    self.driver.execute_script("window.scrollTo(0,345.6000061035156)")
    self.driver.execute_script("window.scrollTo(0,86.4000015258789)")
  
